server:
  port: 9502
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imooc-demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# 关闭session集群
  session:
    store-type: none
# 设置spring security的默认用户名和密码
  security:
    user:
      name: user
      password: 123

# spring-security5.x废弃了下面的配置，已经不生效了
#security:
#  basic:
#    enabled: false

# demo项目的登录页，如果demo项目配置了登录页，就跳转到配置的登录页面，如果demo项目没做配置就跳转到默认的标准登录页
#imooc:
#  security:
#    code:
#      image:
#        length: 6
#        width: 50
#        url: /user,/user/*
#    browser:
#      loginPage: /demo-signIn.html
#      loginType: REDIRECT

