server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imooc-demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# 关闭session集群
  session:
    store-type: none
# 设置spring security的默认用户名和密码
  security:
    user:
      name: user
      password: 123

# spring-security5.x废弃了下面的配置，已经不生效了
#security:
#  basic:
#    enabled: false